version: '3.8'

services:
  # 1. Laravel Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      DB_HOST: db
      DB_DATABASE: job_board_backend
      DB_USERNAME: root
      DB_PASSWORD: ""
    depends_on:
      - db

  # 2. React Frontend (statički build)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "10000:10000"
    depends_on:
      - backend

  # 3. MySQL Database
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: job_board_backend
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql

  # 4. PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_ARBITRARY: 1
    depends_on:
      - db

volumes:
  db_data:
